import {
  Accessibility,
  Activity,
  ArrowRightLeft,
  BadgeCheck,
  Bell,
  Blocks,
  Boxes,
  Cloud,
  CodeXml,
  CreditCard,
  Database,
  Eye,
  FileText,
  Gauge,
  GitBranch,
  Handshake,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  LineChart,
  Lock,
  MapPin,
  MessageSquare,
  MonitorSmartphone,
  Palette,
  PiggyBank,
  Plug,
  Receipt,
  RefreshCw,
  Rocket,
  Search,
  Server,
  ServerCog,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Table2,
  Target,
  Timer,
  TrendingUp,
  Users,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

/** Icons that content can name. Only these are bundled, not the whole lucide set. */
export const icons: Record<string, LucideIcon> = {
  Accessibility,
  Activity,
  ArrowRightLeft,
  BadgeCheck,
  Bell,
  Blocks,
  Boxes,
  Cloud,
  CodeXml,
  CreditCard,
  Database,
  Eye,
  FileText,
  Gauge,
  GitBranch,
  Handshake,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  LineChart,
  Lock,
  MapPin,
  MessageSquare,
  MonitorSmartphone,
  Palette,
  PiggyBank,
  Plug,
  Receipt,
  RefreshCw,
  Rocket,
  Search,
  Server,
  ServerCog,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Table2,
  Target,
  Timer,
  TrendingUp,
  Users,
  Workflow,
  Wrench,
  Zap,
};

/** Renders a content icon by name, matching the design's 2px line icons. */
export function ContentIcon({ name, ...props }: { name: string } & LucideProps) {
  const C = icons[name] ?? CodeXml;
  return <C aria-hidden="true" strokeWidth={2} {...props} />;
}
